remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Introduction to Biometrics
description: |
  Second Edition<br>
  Anil K. Jain, Arun A. Ross, Karthik Nandakumar, Thomas Swearingen
github: false
show_downloads: false
